[general]
title = "DATA"
description = "Data Preprocessing Tool"
favicon = "favicon.ico"

[theme]
base="dark"
backgroundColor="#15171a"
primaryColor = "#1f77b4"
font = "sans serif"

[server]
# Enable/disable CORS protection (default is true)
enableCORS = false
# Maximum upload size (default is 200MB)
maxUploadSize = 200

[logger]
# The log level ("error", "warning", "info", "debug")
level = "info"
# Format for log messages
messageFormat = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
# Format for log time
dateFormat = "%Y-%m-%d %H:%M:%S"
